Add map
vinnieOrdobas/ci_national_ai pull request #49
Opened 2024-09-02 01:34 UTC by sean-meade

2024-09-02 08:00 UTC, vinnieOrdobas requested changes

2024-09-02 08:00 UTC, vinnieOrdobas commented on clientui/src/hackathon/static/route.js
> +  "pk.eyJ1Ijoic2Vhbi1tZWFkZSIsImEiOiJja3lmeDZkM3Iwc21hMm9xcG95YnFqaHh3In0.p4oU6PP7a92U1JYLBCLG2g";
I reckon is best to have this access token in the `.yml` file - perhaps @gomyar can give his two cents on how to pull it here

2024-09-03 17:51 UTC, valerieniloinsigh31 approved these changes

2024-09-03 17:57 UTC, vinnieOrdobas approved these changes
LGTM

2024-09-05 13:50 UTC, merged